[flags]
#dot_marker=true

[[row]]
    ratio=40
    [[row.child]]
      ratio=4
      type="proc"
      default=true
    [[row.child]]
      ratio=3
      [[row.child.child]]
        type="temp"
      [[row.child.child]]
        type="mem"
[[row]]
  ratio=60
  [[row.child]]
  type="cpu"
