set nocompatible                    " be iMproved
filetype off                        " required!

" Vundle Setup
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()
Bundle 'gmarik/vundle'

" My Bundles
Bundle 'bling/vim-airline'
Bundle 'kien/ctrlp.vim'
Bundle 'tpope/vim-fugitive'
Bundle 'guns/xterm-color-table.vim'

" Syntax Highlighting Bundles
Bundle 'kchmck/vim-coffee-script'
Bundle 'digitaltoad/vim-jade'
Bundle 'groenewege/vim-less'

" Colorscheme Plugins
Bundle 'vim-scripts/ScrollColors'
Bundle 'flazz/vim-colorschemes'

filetype plugin indent on           " Vundle Related Magic!


" Vim Theme Settings
syntax enable
set t_Co=256                        " Force 256 Colors
set term=screen-256color
colorscheme twilight256

" I hate vim themes. I want a solid background with a visible cursor, but 
" this is causing me hell. Commenting it out for now so that i can move on
" with my life. In the future i need to figure out two things:
" 1.) How to make a solid dark gray background.
" 2.) How to make the cursor visisble during the background assignment.
"     Currently if i enter `hi Normal ctermbg=black` my cursor disappears,
"     even though *at the moment* my cursor is a bright grey cursor. Makes
"     no sense to me.
"set background=dark
"highlight Normal ctermbg=234

let &colorcolumn=join(range(81,999),",")  " Create a column at 81,82,83,etc
highlight ColorColumn ctermbg=234         " Color the column




" Vim Settings
set shell=sh                        " Set the default shell to sh, this
                                    " fixes my bash->fish in Vim.
set laststatus=2                    " Show the Airline Line

set number                          " Show line numbers
set ruler                           " Show cursor position

set backupdir-=.                    " Remove current dir from the list
set backupdir+=.                    " Append it to the list (so it's checked last)
set backupdir-=~                    " Remove home, if it's in there.. not sure it is?
set backupdir^=~/.vim/tmp/bkp//     " Prepend the bkp dir. Not sure if // syntax
                                    " works with backups.
set backup                          " Turn backup on

set directory=~/.vim/tmp/swp//   	  " Keep swap files in one location.
set directory+=.                    " Add the current directory as a fallback

set tabstop=2       				        " Global tab width
set shiftwidth=2			              " Something involving tab width.
set expandtab				                " Spaces instead of tabs

set foldmethod=indent               " Magic
set foldlevel=20                    " Magic
set foldlevelstart=20               " Magic

autocmd BufNewFile,BufRead *.md set filetype=markdown " Set md to markdown



" CtrlP Settings

let g:ctrlp_extensions = ['line']
let g:ctrlp_show_hidden = 1         " ctrlp will grep hidden files
let g:ctrlp_custom_ignore = {
  \ 'dir': '\.git$\|node_modules$\|bower_components$\|build$',
  \ 'file': '\.exe$\.so$'
  \ }                               " Ignore groups of files.
let g:ctrlp_prompt_mappings = {
  \ 'PrtHistory(-1)': ['<c-up>'],
  \ 'PrtHistory(1)':  ['<c-down>'],
  \ 'ToggleType(1)':  ['<c-p>'],
  \ 'ToggleType(-1)': ['<c-l>'],
  \ 'PrtCurRight()':  ['<right>']
  \ }



" Chrome Specific Remaps


" General Purpose Remaps


" Maps
nmap <silent> <leader>1 :!!<CR>
nmap <silent> <leader>s :set spell!<CR>


