# theme = "monokai_pro_spectrum"
theme = "bogster"

[editor]
line-number = "relative"
idle-timeout = 50
completion-trigger-len = 1
lsp.display-messages = true

[keys.normal]
H = "extend_char_left"
J = "extend_line_down"
K = "extend_line_up"
L = "extend_char_right"
B = "extend_prev_word_start"
W = "extend_next_word_start"
E = "extend_next_word_end"

[keys.normal.g]
i = "goto_first_nonwhitespace"
s = "goto_implementation"
j = "goto_last_line"
k = "goto_file_start"
 
[keys.normal.space]
p = "file_picker" 
P = "no_op"
y = "no_op"
Y = "no_op"
r = "no_op"
S = "no_op"
# jumplist save
s = "save_selection"
j = "jump_backward"
k = "jump_forward"


[keys.normal.space.l]
#e = "goto_next_diag_error"
#E = "goto_prev_diag_error"
w = "goto_next_diag"
W = "goto_prev_diag"
i = "hover"
a = "code_action"
r = "rename_symbol"
j = "goto_definition"
k = "goto_type_definition"
t = "goto_implementation"
s = "symbol_picker"
S = "workspace_symbol_picker"

[keys.normal.space.b]
d = ":buffer-close"
b = "buffer_picker"

[keys.normal.space.'"']
p = "paste_clipboard_after"
P = "paste_clipboard_before"
y = "yank_joined_to_clipboard"
Y = "yank_main_selection_to_clipboard"
 
[keys.normal.space.a]
w = "rotate_view"
s = "vsplit"
v = "hsplit"
f = "goto_file_hsplit"
F = "goto_file_vsplit"
q = "wclose"
o = "wonly"
h = "jump_view_left"
left = "jump_view_left"
j = "jump_view_down"
down = "jump_view_down"
k = "jump_view_up"
up = "jump_view_up"
l =  "jump_view_right"
right = "jump_view_right"
n.s = "vsplit_new"
n.v = "hsplit_new"