" VAM Auto Setup.
set nocompatible | filetype indent plugin on | syn on

fun SetupVAM()
  let c = get(g:, 'vim_addon_manager', {})
  let g:vim_addon_manager = c
  let c.plugin_root_dir = expand('$HOME', 1) . '/.vim/vim-addons'
  let &rtp.=(empty(&rtp)?'':',').c.plugin_root_dir.'/vim-addon-manager'
  " let g:vim_addon_manager = { your config here see "commented version" example and help
  if !isdirectory(c.plugin_root_dir.'/vim-addon-manager/autoload')
    execute '!git clone --depth=1 git://github.com/MarcWeber/vim-addon-manager '
                \       shellescape(c.plugin_root_dir.'/vim-addon-manager', 1)
  endif
  " call vam#ActivateAddons([the plugin names], {'auto_install' : 0})
  " Also See "plugins-per-line" below
endfun
call SetupVAM()
call vam#ActivateAddons([])


" Load plugins using VAM.
ActivateAddons vim-airline
ActivateAddons ctrlp
ActivateAddons Command-T
ActivateAddons fugitive
ActivateAddons vim-coffee-script
ActivateAddons jade



" My Vim Settings
set laststatus=2                    " Show the Airline Line

"set number                          " Show line numbers
set ruler                           " Show cursor position

set directory=$HOME/.vim/tmp//,.	  " Keep swap files in one location.. black magic.

set tabstop=2       				        " Global tab width
set shiftwidth=2			              " Something involving tab width.
set expandtab				                " Spaces instead of tabs

" CtrlP Settings

" Disabled due to .git being searched and causing lag
"let g:ctrlp_show_hidden = 1         " ctrlp will grep hidden files

" Chrome Specific Remaps
"
" These are mappings that have to do with the fact that Chrome sucks.
" .. to elaborate, Chrome consumes a pile of keys and gives you know way
" to actually use them in a webapp. In this case Ctrl-W, Ctrl-T, Ctrl-N,
" and others. Below are remaps that are directly related to that.

nnoremap <C-Q> <C-W>


" General Purpose Remaps
