set nocompatible                    " be iMproved
filetype off                        " required!

" Vundle Setup
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()
Bundle 'gmarik/vundle'

" My Bundles
Bundle 'bling/vim-airline'
Bundle 'kien/ctrlp.vim'
Bundle 'tpope/vim-fugitive'
Bundle 'kchmck/vim-coffee-script'
Bundle 'digitaltoad/vim-jade'

filetype plugin indent on           " Vundle Related Magic!



" Vim Settings
set syntax=on
set laststatus=2                    " Show the Airline Line

"set number                         " Show line numbers
set ruler                           " Show cursor position

set backupdir-=.                    " Remove current dir from the list
set backupdir+=.                    " Append it to the list (so it's checked last)
set backupdir-=~                    " Remove home, if it's in there.. not sure it is?
set backupdir^=~/.vim/tmp/bkp//     " Prepend the bkp dir. Not sure if // syntax
                                    " works with backups.
set backup                          " Turn backup on

set directory=~/.vim/tmp/swp//   	  " Keep swap files in one location.
set directory+=.                    " Add the current directory as a fallback

set tabstop=2       				        " Global tab width
set shiftwidth=2			              " Something involving tab width.
set expandtab				                " Spaces instead of tabs

set foldmethod=indent               " Magic
set foldlevel=20                    " Magic
set foldlevelstart=20               " Magic

autocmd BufNewFile,BufRead *.md set filetype=markdown " Set md to markdown



" CtrlP Settings

let g:ctrlp_extensions = ['line']
let g:ctrlp_show_hidden = 1         " ctrlp will grep hidden files
let g:ctrlp_custom_ignore = {
  \ 'dir': '\.git$\|node_modules$\|bower_components$\|build$',
  \ 'file': '\.exe$\.so$'
  \ }                               " Ignore groups of files.
let g:ctrlp_prompt_mappings = {
  \ 'PrtHistory(-1)': ['<c-up>'],
  \ 'PrtHistory(1)':  ['<c-down>'],
  \ 'ToggleType(1)':  ['<c-p>'],
  \ 'ToggleType(-1)': ['<c-l>'],
  \ 'PrtCurRight()':  ['<right>']
  \ }



" Chrome Specific Remaps
"
" These are mappings that have to do with the fact that Chrome sucks.
" .. to elaborate, Chrome consumes a pile of keys and gives you know way
" to actually use them in a webapp. In this case Ctrl-W, Ctrl-T, Ctrl-N,
" and others. Below are remaps that are directly related to that.

nnoremap <C-Q> <C-W>


" General Purpose Remaps
