#
# # Bashrc
#
# My bashrc is a minimal attempt at getting the hell out of bash as fast
# as possible.
#
PATH=:~/.bin:~/.n/bin:$PATH
N_PREFIX=~/.n
export N_PREFIX

# And go
GOPATH=~/projects/.gocode
GOBIN=$GOPATH/bin
PATH=$GOBIN:$PATH
export GOPATH
export GOBIN
export PATH

# Good god i hate this fucking ixon bullshit. These two lines kill it dead
# before we call tmux.
stty -ixon
stty stop undef

# Alias tmux so i can easily gtfo of bash if i accidentally leave tmux
alias t="tmux attach -t koding"

if [ "$(uname)" == "Linux" ]; then
  t
fi
