#
# # Bash Profile.. KDFramework Friendly
#
# A simple bash profile. It's worth noting that our bash_profile is sourced
# every time the KDF makes a call to our VM. With that said, we want to make
# sure this profile doesn't do any thing crazy like launching other processes,
# but at the same time we need to expose any variables/etc that the KDF (or
# a KDApp) might want.. such as my Node version.
#

# Export our proper Node Versio Junk
PATH=~/.bin:~/.n/bin:$PATH
N_PREFIX=~/.n
export N_PREFIX

# And go
GOPATH=~/projects/.gocode
PATH=$GOPATH/bin:$PATH
export GOPATH
export PATH

# Alias tmux in here as well, so if i SSH in i can gtfo of bash right away.
alias t="tmux attach -t koding"

# Make sure to only auto-run on Mac, since we want Koding's bash_profile not
# to be mean to the Koding Framework calls
if [ "$(uname)" == "Darwin" ]; then
  t
# Here we check if the ssh client var exists, and autolaunch. If it doesn't,
# we don't launch to ensure that it doesn't autorun for KDF
elif [ "$SSH_CLIENT" != "" ]; then
  t
fi
