

# find implements my desire for CtrlP-like fuzzy finder in kakoune.
def find -params 1 -shell-candidates %{ find . -type f -not -path "./vendor/*" -not -path "./.git" } %{ edit %arg{1} }

# This binding replicates my CtrlP usage for the above command.
map global user p ":find "

# I'm quite used to using space as a leader from vim, so using it here too.
map global normal <space> ,
map global normal , <space>

# Set relative line numbers whenever a window is opened.
hook global WinCreate .* %{addhl number_lines -hlcursor -separator ' ' -relative}

# Set the default colorscheme to my custom gruvbox implementation.

# See .config/kak/colors/gruvly.kak for more details.
colorscheme gruvly

# Set the default tab width
set global tabstop 2

# Highlight trailing whitespace
hook global WinCreate .* %{addhl regex '\h+$' 0:default,red}

# Enable automatic modelines for all files. Eg, to adjust settings per file.
hook global BufOpenFile .* %{modeline-parse}

# Enable Golang goimports on file save
hook global BufWritePost .*\.go %{go-format -use-goimports}
