[language.go]
filetypes = ["go"]
roots = ["go.mod", ".git"]
command = "bingo"
args = ["-mode", "stdio", '--logfile', '/tmp/lspserver.log', '--trace', '--pprof', ':6060']

[language.rust]
filetypes = ["rust"]
roots = ["Cargo.toml"]
# Experimenting with RA, but so far it's not great..
command = "rust-analyzer"
#command = "rls"

[language.typescript]
filetypes = ["typescript"]
roots = ["package.json"]
command = "typescript-language-server"
args = ["--stdio"]

[language.typescriptreact]
filetypes = ["typescriptreact"]
roots = ["package.json"]
command = "typescript-language-server"
args = ["--stdio"]
